# Generated by Django 3.1.1 on 2021-07-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_on_date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('rate_per_unit', models.IntegerField()),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METRE', 'METRE')], max_length=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
            ],
        ),
    ]
