# Generated by Django 3.1.1 on 2021-07-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_lineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('gross_quantity', models.DecimalField(decimal_places=10, max_digits=10)),
                ('net_quantity', models.DecimalField(decimal_places=10, max_digits=10)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METRE', 'METRE')], max_length=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.articlemaster')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.companyledgermaster')),
            ],
        ),
    ]
