# Generated by Django 3.1.1 on 2021-07-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210721_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='gross_quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='net_quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
